title: "Animated Progress Ring"
description: "Beautiful circular progress indicators with smooth animations. Includes standard rings, gradient rings, multi-layer rings, segmented rings, and dotted rings. Fully customizable with colors, sizes, line widths, and labels. Perfect for dashboards and progress tracking."
author: "Luiz Mello"
github-username: "luizmellodev"
tags:
  - progress
  - ring
  - circular
  - animation
  - chart
