title: Minimal Login
author: Luiz Mello
github-username: luizmellodev
tags:
  - login
  - button
  - ui
description: A minimal login screen with a beautiful gradient background and a beautiful button
