title: Accordion Component
author: Luiz Mello
github-username: luizmellodev
tags:
  - animation
  - ui
  - component
description: A customizable accordion component with smooth animations, multiple expansion modes, and custom styling options perfect for FAQs and collapsible content
