title: Onboarding Swipe View
author: Luiz Mello
github-username: luizmellodev
tags:
  - navigation
  - animation
  - gesture
description: A beautiful swipeable onboarding screen with page indicators, smooth animations, and gradient backgrounds
