title: "Shimmer Button"
description: "Beautiful animated buttons with shimmer/shine effects. Includes default shimmer, gradient shimmer with rotating colors, and pulse shimmer with expanding rings. Fully customizable with haptic feedback and smooth animations."
author: "Luiz Mello"
github-username: "luizmellodev"
tags:
  - button
  - animation
  - shimmer
  - gradient
  - interaction
