title: "Wave Animation"
description: "Versatile wave animations for dynamic UIs. Includes simple waves, filled waves, multi-layer waves, wave loading indicators, wave progress bars, circular waves, audio visualizers, and wave backgrounds. Fully customizable with colors, speeds, and amplitudes."
author: "Luiz Mello"
github-username: "luizmellodev"
tags:
  - wave
  - animation
  - loading
  - progress
  - effect
