title: "Gradient Border Card"
description: "Stunning cards with animated gradient borders. Includes rotating gradients, glowing borders, dashed borders, pulsing effects, neon borders, and shimmer effects. Multiple preset styles (rainbow, fire, ocean, sunset) and fully customizable. Perfect for premium features and special content."
author: "Luiz Mello"
github-username: "luizmellodev"
tags:
  - card
  - gradient
  - border
  - animation
  - effect
