title: Colorful Shadow Button
author: Luiz Mello
github-username: luizmellodev
tags:
  - animation
  - button
  - ui
description: An animated button with continuously changing colorful shadow effects using gradient animations
